management:
  server:
    port: 8080
  endpoint:
    health:
      probes:
        enabled: true
  tracing:
    sampling:
      probability: 1.0

spring:
  application:
    name: poc-webflux-native
---
spring:
  config:
    activate:
      on-cloud-platform: kubernetes
logging:
  structured:
    format:
      console: ecs
