name: Build source code

on:
  workflow_call:

permissions:
  pull-requests: read
  contents: read
  security-events: write
  packages: write

defaults:
  run:
    working-directory: ./code

jobs:
  build:
    name: Build Maven artifact
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set-up GraalVM
        uses: actions/setup-java@v4.7.1
        with:
          java-version: '21'
          distribution: 'graalvm'
          cache: 'maven'
      - name: Cache SonarCloud packages
        uses: actions/cache@v4
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar
      - name: Build & Test
        run: ./mvnw -B clean verify
      - name: Run SonarCloud analysis
        if: github.actor != 'dependabot[bot]'
        run: >
          ./mvnw -B sonar:sonar
          -Dsonar.organization=${{ vars.SONAR_ORGANIZATION }}
          -Dsonar.projectKey=${{ vars.SONAR_PROJECT_KEY_CODE }}
          -Dsonar.host.url=${{ vars.SONAR_HOST_URL }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      - name: Run Snyk analysis in source code
        run: ./mvnw -B snyk:test
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      - name: Upload source code analysis results to GitHub
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: ./code/code.sarif
          category: source-code
